version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
  webserver:
    build: .
    depends_on:
      - db
    volumes:
      - ./www/:/var/www/
    ports:
      - "80:80"
      - "443:443"
    stdin_open: true
    tty: true